spring:
  datasource:
    url: jdbc:h2:~/fiapdb4;DB_CLOSE_ON_EXIT=FAlSE
    username: fiapuser
    password: fiap
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: fiap
  expire: 1